#ifndef VDOMTYPESPLUGIN_GLOBAL_H
#define VDOMTYPESPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VDOMTYPESPLUGIN_LIBRARY)
#  define VDOMTYPESPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VDOMTYPESPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VDOMTYPESPLUGIN_GLOBAL_H
